<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

/**
 * Confirmation email sent to a platform admin when they request to
 * impersonate a school. The OTP is what they type into the saas-admin
 * panel to actually receive the handoff code. Without successfully
 * entering this OTP no impersonation token is issued — so even a
 * stolen platform-admin Sanctum token cannot impersonate without
 * also having access to the admin's inbox.
 */
class PlatformImpersonationOtpMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(
        public string $adminName,
        public string $schoolName,
        public string $otp,
        public int $expiryMinutes,
        public string $requestSource = 'platform admin panel'
    ) {}

    public function build()
    {
        return $this
            ->subject('Confirm impersonation — ' . $this->schoolName)
            ->html($this->renderHtml());
    }

    /**
     * Inlined HTML so this doesn't depend on the per-school EmailTemplate
     * system (which is school-scoped). Platform emails are unbranded by
     * design — they come from the SaaS operator, not from any tenant.
     */
    private function renderHtml(): string
    {
        $name = e($this->adminName);
        $school = e($this->schoolName);
        $otp = e($this->otp);
        $mins = (int) $this->expiryMinutes;
        $source = e($this->requestSource);

        return <<<HTML
<!doctype html>
<html>
<body style="font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; max-width: 480px; margin: 24px auto; color: #0f172a; line-height: 1.5;">
  <p>Hi {$name},</p>
  <p>You requested to enter a school as its administrator from the {$source}. Use the one-time code below to confirm and complete the handoff:</p>
  <p style="font-size: 32px; letter-spacing: 8px; font-weight: 800; text-align: center; margin: 24px 0; color: #4f46e5; background: #eef2ff; padding: 16px; border-radius: 8px;">
    {$otp}
  </p>
  <p>School: <strong>{$school}</strong><br>Code expires in <strong>{$mins} minutes</strong>.</p>
  <p style="color: #b91c1c;">If you didn't request this, ignore this email and immediately rotate your platform admin password — your account session may be compromised.</p>
  <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 24px 0;">
  <p style="font-size: 12px; color: #64748b;">This message was generated by the SaaS platform admin console. Every impersonation request and its completion is recorded in the platform audit log.</p>
</body>
</html>
HTML;
    }
}
