<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class PlatformAdminLoginOtpMail extends Mailable
{
    use Queueable, SerializesModels;

    public function __construct(
        public string $adminName,
        public string $otp,
        public int $expiryMinutes
    ) {}

    public function build()
    {
        return $this
            ->subject('GradoX Platform Admin — One-Time Login Code')
            ->html($this->renderHtml());
    }

    private function renderHtml(): string
    {
        $name = e($this->adminName);
        $otp = e($this->otp);
        $mins = (int) $this->expiryMinutes;

        return <<<HTML
<!doctype html>
<html>
<body style="font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; max-width: 480px; margin: 24px auto; color: #0f172a; line-height: 1.5;">
  <p>Hi {$name},</p>
  <p>Use the one-time verification code below to log in to the GradoX Platform Admin panel:</p>
  <p style="font-size: 32px; letter-spacing: 8px; font-weight: 800; text-align: center; margin: 24px 0; color: #4f46e5; background: #eef2ff; padding: 16px; border-radius: 8px;">
    {$otp}
  </p>
  <p>This code expires in <strong>{$mins} minutes</strong>.</p>
  <p style="color: #b91c1c;">If you did not request this code, please secure your email account immediately. Only authorized platform staff should access this console.</p>
  <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 24px 0;">
  <p style="font-size: 12px; color: #64748b;">This message was generated by the SaaS platform admin console. Every login attempt is audited.</p>
</body>
</html>
HTML;
    }
}
